package com.example.onlineshop.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WishListAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishListAllPropertiesEquals(WishList expected, WishList actual) {
        assertWishListAutoGeneratedPropertiesEquals(expected, actual);
        assertWishListAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishListAllUpdatablePropertiesEquals(WishList expected, WishList actual) {
        assertWishListUpdatableFieldsEquals(expected, actual);
        assertWishListUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishListAutoGeneratedPropertiesEquals(WishList expected, WishList actual) {
        assertThat(actual)
            .as("Verify WishList auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishListUpdatableFieldsEquals(WishList expected, WishList actual) {
        assertThat(actual)
            .as("Verify WishList relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getRestricted()).as("check restricted").isEqualTo(expected.getRestricted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWishListUpdatableRelationshipsEquals(WishList expected, WishList actual) {
        assertThat(actual)
            .as("Verify WishList relationships")
            .satisfies(a -> assertThat(a.getProducts()).as("check products").isEqualTo(expected.getProducts()))
            .satisfies(a -> assertThat(a.getCustomer()).as("check customer").isEqualTo(expected.getCustomer()));
    }
}
